### ISSUE TITLE
Pinned oqpy version breaks tensorflow imports

### ISSUE THREAD

**Issue by dcanuto** [aws/amazon-braket-sdk-python#473]
**Describe the bug**
The `oqpy` version specified as a dependency (`0.1.0`) pins `numpy==1.21.6`. Recent versions of `tensorflow-macos` compile against newer versions of `numpy`, causing subsequent `tensorflow` imports to fail.

**To reproduce**
From within a fresh `conda` virtual environment on `python 3.9.13`, I ran:
```
python -m pip install amazon-braket-sdk
python -m pip install tensorflow-macos
python
>>> import tensorflow as tf
```
The `import` statement results in:
```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 24, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 23, in <module>
    from tensorflow.python.data.util import nest
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 36, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/framework/sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 23, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/danielcanuto/miniconda3/envs/dep-bug/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py", line 34, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
```

**Expected behavior**
To be able to import `tensorflow`.

**System information**
- **Amazon Braket Python SDK version**: 1.33.0.post0
- **Amazon Braket Python Schemas version**: 1.12.0
- **Amazon Braket Python Default Simulator version**: 1.10.0
- **Python version**: 3.9.13

**Additional context**
I don't know if it would break things elsewhere, but `oqpy 0.1.1` has relaxed its `numpy` version requirement in a way that's compatible with `tensorflow-macos`. In other words, in a fresh virtual environment, the following works:
```
python -m pip install oqpy==0.1.1
python -m pip install tensorflow-macos
python
>>> import tensorflow as tf
>>> print(tf.reduce_sum(tf.random.normal([1000, 1000])))
tf.Tensor(-1386.055, shape=(), dtype=float32)
```

**Comment by math411** [comment]
Hello, we are in the process of making the update to oqpy v0.1.1. This can be tracked with https://github.com/aws/amazon-braket-sdk-python/pull/469.

**Comment by ajberdy** [comment]
Oqpy update is complete, marking this issue as resolved. Feel free to reopen if there are still issues!
